### PR TITLE
[MINI-5697] SampleApp Unable to open any contact from settings

### PR DESCRIPTION
**Pull request by GondiTilak**
# Description
Issue: Unable to open any contact from settings and edit the contact details.
Cause: onTapGesture handler was missing for the List view cells in new SwiftUI implementation
Fix: Added onTapGesture for the Contacts List cell, On tap the edit contact will be presented and can edit the contact and save it.

## Links
https://jira.rakuten-it.com/jira/browse/MINI-5697
Fix Demo: https://rak.box.com/s/b75zt50q5fltqmhxi3edqceykhmwy7zl
PR comments implementation demo : https://rak.box.com/s/bpbqycag0yvefuhr6csdqxrj4vqmhmax

# Checklist
- [x] I have read the [contributing guidelines](CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](CONTRIBUTING.md#SDK-Development-Learning-Path) (if submitting a feature PR)
- [ ] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [ ] I ran `fastlane ci` without errors

### CODE REVIEW

**Review by rleojoseph — CHANGES_REQUESTED** [review]
Changes looks fine. But are we doing the validations before saving the contacts here?

* Validate Contact ID & Name is not empty before saving
* Verify the EmailID entered is a valid Email ID. (We have used a regex for the same in the old demo app)

**Comment by GondiTilak** [comment]
> 

Requested changes as per the comments are now implemented in the commit 1b83a4ba01f5c541c96062ed5b00d6232ae5f973, please review.

**Review by Climbatize — APPROVED** [review]
Nice job

**Comment by laubengaier** [comment]
@GondiTilak as discussed for the simplification

```swift
class CustomMAContact: MAContact {

	var index: Int?

	init(id: String, name: String? = nil, email: String? = nil, index: Int?) {
		super.init(id: id, name: name, email: email)
		self.index = index
	}

	required init(from decoder: Decoder) throws {
		fatalError("init(from:) has not been implemented")
	}
}

//...
@State var newContact: CustomMAContact? // could be renamed to editContact

//... List
ContactCellView(
    name: contact.name ?? "",
    contactId: contact.id,
    email: contact.email ?? "",
    isNew: contact.wrappedValue.index == nil
)
.onTapGesture {
    guard let index = contact.wrappedValue.index else { return }
    newContact = contacts[index]
}

//... onSave
if let index = contact.index {
	contacts[index] = contact
} else {
	contacts.insert(contact, at: 0)
	contact.index = 0
}
newContact = nil
viewModel.saveContactList(contacts: contacts)

//... getContacts
func getContacts() -> [CustomMAContact] {
  (getContactList() ?? [])
	.enumerated()
	.map({ CustomMAContact(id: $0.element.id, name: $0.element.name, email: $0.element.email, index: $0.offset)})
}
```

**Comment by GondiTilak** [comment]
> @GondiTilak as discussed for the simplification
> 
> ```swift
> class CustomMAContact: MAContact {
> 
> 	var index: Int?
> 
> 	init(id: String, name: String? = nil, email: String? = nil, index: Int?) {
> 		super.init(id: id, name: name, email: email)
> 		self.index = index
> 	}
> 
> 	required init(from decoder: Decoder) throws {
> 		fatalError("init(from:) has not been implemented")
> 	}
> }
> 
> //...
> @State var newContact: CustomMAContact? // could be renamed to editContact
> 
> //... List
> ContactCellView(
>     name: contact.name ?? "",
>     contactId: contact.id,
>     email: contact.email ?? "",
>     isNew: contact.wrappedValue.index == nil
> )
> .onTapGesture {
>     guard let index = contact.wrappedValue.index else { return }
>     newContact = contacts[index]
> }
> 
> //... onSave
> if let index = contact.index {
> 	contacts[index] = contact
> } else {
> 	contacts.insert(contact, at: 0)
> 	contact.index = 0
> }
> newContact = nil
> viewModel.saveContactList(contacts: contacts)
> 
> //... getContacts
> func getContacts() -> [CustomMAContact] {
>   (getContactList() ?? [])
> 	.enumerated()
> 	.map({ CustomMAContact(id: $0.element.id, name: $0.element.name, email: $0.element.email, index: $0.offset)})
> }
> ```

Made the code changes as per our discussions please review.

**Review by laubengaier — APPROVED** [review]
well done!! lgtm

**Comment by GondiTilak** [comment]
> Changes looks fine. But are we doing the validations before saving the contacts here?
> 
> * Validate Contact ID & Name is not empty before saving
> * Verify the EmailID entered is a valid Email ID. (We have used a regex for the same in the old demo app)

Validations have ben applied in the latest checkin c81177ca0c09f56cb0a57a3bb456ee676d3881a5

**Review by rleojoseph — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
