### PR TITLE
[MINI-5814] [iOS SDK] Support multiple e-mail addresses for a contact

### PR DESCRIPTION
**Pull request by GondiTilak**
# Description
Support multiple e-mail addresses for a contact.
Issue: SDK supports sharing only one email address of a specific contact
Cause: MiniApp SDK Contact object only supports 1 e-mail address by contact
Fix: Adding the ability to provide the complete list of e-mail addresses for a contact with the new variable public var allEmailList: [String]? to MAContact struct.

## Links
[MINI-5814](https://jira.rakuten-it.com/jira/browse/MINI-5814)

# Checklist
- [x] I have read the [contributing guidelines](CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](CONTRIBUTING.md#SDK-Development-Learning-Path) (if submitting a feature PR)
- [ ] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [ ] I ran `fastlane ci` without errors

### CODE REVIEW

**Review by Climbatize — APPROVED** [review]
LGTM

**Review by rleojoseph — APPROVED** [review]
Thank you for the changes. Could you please update the CHANGELOG file as well

**Comment by Climbatize** [comment]
Please add doc and tests

**Review by rleojoseph — CHANGES_REQUESTED** [review]
Could you please update the testcases. I see coverage is dropped by %

**Comment by GondiTilak** [comment]
> Could you please update the testcases. I see coverage is dropped by %

I have added some new test cases to improve the coverage please review the changes. Also the coverage drop was not related to any of the new code changes I guess.

**Comment by GondiTilak** [comment]
> Please add doc and tests

I have updated the change doc please review.

**Review by rleojoseph — APPROVED** [review]
Looks good to me :+1: Thank you for the changes

**Pull request merged**
