### PR TITLE
Refactor Sample app files location

### PR DESCRIPTION
**Pull request by ts-leojoseph-r**
# Description
Sample app files were moved to SDK Directory. Now it has been put in the right place.

# Checklist
- [x] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [ ] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `fastlane ci` without errors

### CODE REVIEW

**Comment by corycaywood** [comment]
I think something's wrong with the `js-miniapp` submodule. It looks like it's referencing a commit which doesn't exist.

**Comment by ts-leojoseph-r** [comment]
> I think something's wrong with the `js-miniapp` submodule. It looks like it's referencing a commit which doesn't exist.

Yeah, looks like in previous PR it was removed. Now added back.

**Review by corycaywood — APPROVED** [review]
👍

**Review by Climbatize — APPROVED** [review]
LGTM

**Pull request merged**
