### PR TITLE
Refactor sample app and update Danger

### PR DESCRIPTION
**Pull request by ts-leojoseph-r**
# Description
* Updated Danger version
* Refactored `getConfig` -> `getCurrentConfig`

# Checklist
- [x] I have read the [contributing guidelines](CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](CONTRIBUTING.md#SDK-Development-Learning-Path) (if submitting a feature PR)
- [ ] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `fastlane ci` without errors

### CODE REVIEW

**Review by Climbatize — APPROVED** [review]
to me the dot (`.`) means `get` and `set`, so it should not be necessary to repeat it, e.g: `Config.getCurrent()` -> `Config.current()`. As for the change from `getCurrent()` to `getCurrentConfig()`, as we are in an object called Config, I feel it's redundant. But this is only my personal opinion, and this change only affects demo app so it does not bother me, so feel free to merge it :)

**Comment by ts-leojoseph-r** [comment]
> to me the dot (`.`) means `get` and `set`, so it should not be necessary to repeat it, e.g: `Config.getCurrent()` -> `Config.current()`. As for the change from `getCurrent()` to `getCurrentConfig()`, as we are in an object called Config, I feel it's redundant. But this is only my personal opinion, and this change only affects demo app so it does not bother me, so feel free to merge it :)

I agree. For me, (`.`) means only `get` method, for `set` its better to add `set` prefix like apple does already. Update feedback changes

**Review by corycaywood — APPROVED** [review]
LGTM 👍

**Review by Climbatize — APPROVED** [review]
🙇‍♂️

**Pull request merged**
