### PR TITLE
[MINI-3294] Deep linking Error Screens

### PR DESCRIPTION
**Pull request by rleojoseph**
# Description
* Added Error UI's for Deeplink Error flows

<table>
<tr>
<td>
    
</td>
<td>
    
</td>
</tr>
<td></<td>
<tr>
<td>
    
</td>
<td>
    
</td>
<td>
    
</td>
</tr>
</table>

## Links
[MINI-3294](https://jira.rakuten-it.com/jira/browse/MINI-3294)

# Checklist
- [x] I have read the [contributing guidelines](CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](CONTRIBUTING.md#SDK-Development-Learning-Path) (if submitting a feature PR)
- [ ] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `fastlane ci` without errors

### CODE REVIEW

**Review by Climbatize — COMMENTED** [review]
Hey Leo, by chance could you add some screenshots or a video to show us the behavior of your new screens?

**Comment by rleojoseph** [comment]
> Hey Leo, by chance could you add some screenshots or a video to show us the behavior of your new screens?

@Climbatize Updated screenshots.

**Review by Climbatize — APPROVED** [review]
looks very good, nice job

**Review by corycaywood — APPROVED** [review]
Looks good 👍

**Pull request merged**
