### PR TITLE
[MINI-3056] Remove Danger

### PR DESCRIPTION
**Pull request by rleojoseph**
# Description
Removing Danger from the project as it will be not used for coverage.
Planning on bringing Code Cov for Code Quality.

## Links
MINI-3056

# Checklist
- [x] I have read the [contributing guidelines](CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](CONTRIBUTING.md#SDK-Development-Learning-Path) (if submitting a feature PR)
- [ ] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `fastlane ci` without errors

### CODE REVIEW

**Review by corycaywood — COMMENTED** [review]
Could you also update this PR with the change for enabling code-cov?

I don't think we should completely remove Danger until we have something working for code coverage.

**Comment by rleojoseph** [comment]
> Could you also update this PR with the change for enabling code-cov?
> 
> I don't think we should completely remove Danger until we have something working for code coverage.

@corycaywood We update the workflow in CI to post the Code coverage details. So couldn't include anything in this PR. Do you want to revert back the changes related to Danger ?

**Comment by corycaywood** [comment]
> @corycaywood We update the workflow in CI to post the Code coverage details. So couldn't include anything in this PR. Do you want to revert back the changes related to Danger ?

Ah, okay I see - the codecov publishing is in the Bitrise config, so it should be okay to remove Danger.

But I still don't see any new coverage published here: https://app.codecov.io/gh/rakutentech/ios-miniapp
Maybe there haven't been any builds yet which published coverage?

**Review by corycaywood — APPROVED** [review]
👍

**Comment by rleojoseph** [comment]
> > @corycaywood We update the workflow in CI to post the Code coverage details. So couldn't include anything in this PR. Do you want to revert back the changes related to Danger ?
> 
> Ah, okay I see - the codecov publishing is in the Bitrise config, so it should be okay to remove Danger.
> 
> But I still don't see any new coverage published here: https://app.codecov.io/gh/rakutentech/ios-miniapp
> Maybe there haven't been any builds yet which published coverage?

Yeah, the coverage chart isn't showing the recent changes(Maybe it will show after the merge to master ). But I see this PR is showing in recent commits, which should be ok for now.

**Review by Climbatize — APPROVED** [review]
I thought I reviewed this one, sorry for the delay ;)

**Pull request merged**
