### PR TITLE
Updated delegates in Sample app

### PR DESCRIPTION
**Pull request by rleojoseph**
# Description
Looks like I forgot to update the delegate in sample app. This PR will fix it.

## Links
Add links to github/jira issues, design documents and other relevant resources (e.g. previous discussions, platform/tool documentation etc.)

# Checklist
- [x] I have read the [contributing guidelines](CONTRIBUTING.md).
- [x] I have completed the [SDK Development Learning Path](CONTRIBUTING.md#SDK-Development-Learning-Path) (if submitting a feature PR)
- [ ] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `fastlane ci` without errors

### CODE REVIEW

**Review by Climbatize — APPROVED** [review]
My bad, I should have worried about this. Also really smart way to delete ghost methods 🤣

**Comment by rleojoseph** [comment]
> My bad, I should have worried about this. Also really smart way to delete ghost methods 🤣

We have a default implementation for these delegates, that's why Xcode thought it was a normal function 😞

**Review by khairul-alam-licon — APPROVED** [review]
👍

**Review by laubengaier — APPROVED** [review]
nice catch 🎣

**Pull request merged**
