### PR TITLE
JS Bridge updates for Custom Permission support

### PR DESCRIPTION
**Pull request by corycaywood**
# Description
- build: Update JS Bridge submodule to latest version
  - This fixes an issue where the response was being returned to the user as as string rather than an object
- refactor: (Custom permissions) Rename 'isGranted' param to 'status'
  - This param doesn't represent a boolean - it represents a status of allowed, denied, or not available so it should be named accordingly.

# Checklist
- [x] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [ ] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `fastlane ci` without errors

### CODE REVIEW

**Review by ts-leojoseph-r — APPROVED** [review]
Looks good to me :+1:

**Review by Climbatize — APPROVED** [review]
Good ! I always prefer enum than booleans for statuses, we never know

**Comment by ts-leojoseph-r** [comment]
> Good ! I always prefer enum than booleans for statuses, we never know

@Climbatize was it boolean before 🤷

**Review by khairul-alam-licon — APPROVED** [review]
👍

**Pull request merged**
