### PR TITLE
updates changelog for version 2.6.0

### PR DESCRIPTION
**Pull request by Climbatize**
# Description
- updates changelog for version 2.6.0
- increments pod version number

### CODE REVIEW

**Review by khairul-alam-licon — APPROVED** [review]
👍

**Review by ts-leojoseph-r — CHANGES_REQUESTED** [review]
Please update `Info.plist` as well

**Review by corycaywood — APPROVED** [review]
LGTM 👍

**Review by ts-leojoseph-r — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
