### PR TITLE
Feat/share msg content

### PR DESCRIPTION
**Pull request by ts-leojoseph-r**
# Description
* SDK: Share message from Miniapp through host app via public interface. Host app will use UIActitivityController to display the sharing options.
* Sample app: Implementation to show the sharing feature
* Updated submodule as well.
* Updated codecov

## Links
[MINI-1595](https://jira.rakuten-it.com/jira/browse/MINI-1595)

# Checklist
- [x] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [x] I wrote/updated tests for new/changed code
- [x] I removed all sensitive data before every commit, including API endpoints and keys
- [x] I ran `fastlane ci` without errors

### CODE REVIEW

**Review by corycaywood — APPROVED** [review]
Looks good 👍

**Comment by corycaywood** [comment]
Could you also add this to the change log?

**Comment by ts-leojoseph-r** [comment]
> Could you also add this to the change log?

Done

**Review by Climbatize — APPROVED** [review]
Nice feature

**Pull request merged**
